// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// peakPickingBfGC
NumericMatrix peakPickingBfGC(double mz, double mz_step, std::vector<double> XIC, std::vector<double> scantime, double min_intensity, int sn, int noisescans, double peakwidth_min, double peakwidth_max, int maxPeaksPerSignal);
RcppExport SEXP _shewhart4hrms_peakPickingBfGC(SEXP mzSEXP, SEXP mz_stepSEXP, SEXP XICSEXP, SEXP scantimeSEXP, SEXP min_intensitySEXP, SEXP snSEXP, SEXP noisescansSEXP, SEXP peakwidth_minSEXP, SEXP peakwidth_maxSEXP, SEXP maxPeaksPerSignalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< double >::type mz_step(mz_stepSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type XIC(XICSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type scantime(scantimeSEXP);
    Rcpp::traits::input_parameter< double >::type min_intensity(min_intensitySEXP);
    Rcpp::traits::input_parameter< int >::type sn(snSEXP);
    Rcpp::traits::input_parameter< int >::type noisescans(noisescansSEXP);
    Rcpp::traits::input_parameter< double >::type peakwidth_min(peakwidth_minSEXP);
    Rcpp::traits::input_parameter< double >::type peakwidth_max(peakwidth_maxSEXP);
    Rcpp::traits::input_parameter< int >::type maxPeaksPerSignal(maxPeaksPerSignalSEXP);
    rcpp_result_gen = Rcpp::wrap(peakPickingBfGC(mz, mz_step, XIC, scantime, min_intensity, sn, noisescans, peakwidth_min, peakwidth_max, maxPeaksPerSignal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shewhart4hrms_peakPickingBfGC", (DL_FUNC) &_shewhart4hrms_peakPickingBfGC, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_shewhart4hrms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
